from __future__ import annotations

MODE_NORMAL = "NORMAL"
MODE_INSERT = "INSERT"
MODE_COMMAND = "COMMAND"
MODE_VISUAL = "VISUAL"
MODE_FUZZY = "FUZZY"
MODE_FLOAT_LIST = "FLOAT_LIST"
MODE_EXPLORER = "EXPLORER"
MODE_COMPLETION = "COMPLETION"
MODE_KEY_HINTS = "KEY_HINTS"
MODE_ALERT = "ALERT"
MODE_LIVE_GREP = "LIVE_GREP"
